-- District catalog (Telegram Mini App)
-- Shared, unowned rows. Guest poster is users.id = 1.

CREATE TABLE IF NOT EXISTS users (
    id                BIGINT        PRIMARY KEY,
    username          VARCHAR(32),
    first_name        VARCHAR(255),
    last_name         VARCHAR(255),
    created_at        TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    deleted_at        TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS service_categories (
    id          INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug        VARCHAR(32)   NOT NULL,
    title       VARCHAR(64)   NOT NULL,
    sort_order  SMALLINT      NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    deleted_at  TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_service_categories_slug_alive
    ON service_categories (slug)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS companies (
    id                INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(255)  NOT NULL,
    description       TEXT,
    rating_value      NUMERIC(3, 2) NOT NULL DEFAULT 0.00,
    rating_count      INTEGER       NOT NULL DEFAULT 0,
    create_user       BIGINT,
    created_at        TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    deleted_at        TIMESTAMPTZ,
    CONSTRAINT fk_companies_create_user
        FOREIGN KEY (create_user) REFERENCES users (id)
        ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS services (
    id                INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id       INTEGER       NOT NULL,
    name              VARCHAR(255)  NOT NULL,
    description       TEXT,
    price_cents       INTEGER,
    price_note        VARCHAR(64),
    rating_value      NUMERIC(3, 2) NOT NULL DEFAULT 0.00,
    rating_count      INTEGER       NOT NULL DEFAULT 0,
    create_user       BIGINT,
    created_at        TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    deleted_at        TIMESTAMPTZ,
    CONSTRAINT fk_services_category
        FOREIGN KEY (category_id) REFERENCES service_categories (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_services_create_user
        FOREIGN KEY (create_user) REFERENCES users (id)
        ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_services_category_alive
    ON services (category_id)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS rating_reviews (
    id           INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id   INTEGER,
    service_id   INTEGER,
    create_user  BIGINT        NOT NULL,
    author_name  VARCHAR(64)   NOT NULL DEFAULT 'Житель',
    rating       SMALLINT      NOT NULL CHECK (rating BETWEEN 1 AND 5),
    review_text  TEXT,
    create_date  TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    deleted_at   TIMESTAMPTZ,
    CONSTRAINT chk_review_one_parent CHECK (
        (company_id IS NOT NULL AND service_id IS NULL)
        OR
        (company_id IS NULL AND service_id IS NOT NULL)
    ),
    CONSTRAINT fk_reviews_company
        FOREIGN KEY (company_id) REFERENCES companies (id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_reviews_service
        FOREIGN KEY (service_id) REFERENCES services (id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_reviews_create_user
        FOREIGN KEY (create_user) REFERENCES users (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS photos (
    id              INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id       INTEGER,
    service_id      INTEGER,
    company_id      INTEGER,
    image_url       TEXT          NOT NULL,
    sort_order      SMALLINT      NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    deleted_at      TIMESTAMPTZ,
    CONSTRAINT chk_photo_one_parent CHECK (
        (review_id IS NOT NULL AND service_id IS NULL AND company_id IS NULL)
        OR
        (review_id IS NULL AND service_id IS NOT NULL AND company_id IS NULL)
        OR
        (review_id IS NULL AND service_id IS NULL AND company_id IS NOT NULL)
    ),
    CONSTRAINT fk_photos_review
        FOREIGN KEY (review_id) REFERENCES rating_reviews (id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_photos_service
        FOREIGN KEY (service_id) REFERENCES services (id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_photos_company
        FOREIGN KEY (company_id) REFERENCES companies (id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

INSERT INTO users (id, username, first_name) VALUES
    (1, 'guest', 'Житель'),
    (2, 'anna', 'Анна'),
    (3, 'marina', 'Марина'),
    (4, 'olga', 'Ольга'),
    (5, 'ivan', 'Иван')
ON CONFLICT (id) DO NOTHING;

INSERT INTO service_categories (slug, title, sort_order)
SELECT v.slug, v.title, v.sort_order
FROM (VALUES
    ('beauty', 'Красота', 10),
    ('food', 'Еда', 20),
    ('repair', 'Ремонт', 30),
    ('cleaning', 'Уборка', 40),
    ('childcare', 'Дети', 50),
    ('pets', 'Животные', 60),
    ('education', 'Репетиторы', 70),
    ('transport', 'Переезды', 80),
    ('health', 'Здоровье', 90),
    ('other', 'Другое', 100)
) AS v(slug, title, sort_order)
WHERE NOT EXISTS (
    SELECT 1 FROM service_categories s WHERE s.slug = v.slug AND s.deleted_at IS NULL
);

INSERT INTO services (category_id, name, description, price_cents, price_note, rating_value, rating_count, create_user)
SELECT c.id, v.name, v.description, v.price_cents, v.price_note, v.rating_value, v.rating_count, v.create_user
FROM (VALUES
    ('beauty', 'Маникюр у дома', 'Аппаратный маникюр, покрытие гель-лак. Выезд по Восточному Бутово 2, запись в личные сообщения.', 150000, NULL, 4.80, 3, 2),
    ('beauty', 'Брови и ресницы', 'Ламинирование бровей, окрашивание, оформление. Работаю в своей квартире, корпус 3.', 80000, NULL, 4.50, 2, 3),
    ('beauty', 'Стрижка женская', 'Каре, укладка, детские стрижки. Инструмент свой, выезд по району.', NULL, 'договорная', 4.20, 1, 4),
    ('food', 'Домашние пельмени', 'Пельмени и борщ на заказ. Порции от 10 штук, доставка по району вечером.', 45000, 'от 450 ₽', 4.90, 2, 4),
    ('repair', 'Мелкий бытовой ремонт', 'Розетки, смесители, сборка мебели. Вечер после 18:00, инструмент свой.', 120000, NULL, 4.60, 2, 5),
    ('cleaning', 'Уборка квартиры', 'Поддерживающая и генеральная. Свои средства, 2–4 часа.', 250000, NULL, 4.70, 1, 3),
    ('childcare', 'Няня на вечер', 'Посидеть с ребёнком 3–8 лет, прогулка во двор, уроки. Соседка из 12 подъезда.', 60000, 'от 600 ₽/час', 5.00, 1, 2)
) AS v(slug, name, description, price_cents, price_note, rating_value, rating_count, create_user)
JOIN service_categories c ON c.slug = v.slug
WHERE NOT EXISTS (SELECT 1 FROM services s WHERE s.name = v.name);

INSERT INTO companies (name, description, rating_value, rating_count, create_user)
SELECT v.name, v.description, v.rating_value, v.rating_count, v.create_user
FROM (VALUES
    ('Пятёрочка на Полянах', 'Продукты, готовка, пекарня. Открыто до 23:00.', 4.10, 2, 1),
    ('Аптека у дома', 'Лекарства, детское питание, очередь обычно короткая.', 4.60, 2, 1),
    ('Детский клуб «Светлячок»', 'Развивающие занятия 3–6 лет, суббота утром.', 4.90, 1, 4)
) AS v(name, description, rating_value, rating_count, create_user)
WHERE NOT EXISTS (SELECT 1 FROM companies c WHERE c.name = v.name);

INSERT INTO photos (service_id, image_url, sort_order)
SELECT s.id, v.url, v.sort_order
FROM (VALUES
    ('Маникюр у дома', '/photos/manicure.jpg', 0),
    ('Брови и ресницы', '/photos/brows.jpg', 0),
    ('Стрижка женская', '/photos/hair.jpg', 0),
    ('Домашние пельмени', '/photos/food.jpg', 0),
    ('Мелкий бытовой ремонт', '/photos/repair.jpg', 0),
    ('Уборка квартиры', '/photos/cleaning.jpg', 0),
    ('Няня на вечер', '/photos/kids.jpg', 0)
) AS v(name, url, sort_order)
JOIN services s ON s.name = v.name
WHERE NOT EXISTS (
    SELECT 1 FROM photos p WHERE p.service_id = s.id AND p.image_url = v.url
);

INSERT INTO photos (company_id, image_url, sort_order)
SELECT c.id, v.url, v.sort_order
FROM (VALUES
    ('Пятёрочка на Полянах', '/photos/shop.jpg', 0),
    ('Аптека у дома', '/photos/pharmacy.jpg', 0),
    ('Детский клуб «Светлячок»', '/photos/kids.jpg', 0)
) AS v(name, url, sort_order)
JOIN companies c ON c.name = v.name
WHERE NOT EXISTS (
    SELECT 1 FROM photos p WHERE p.company_id = c.id AND p.image_url = v.url
);

INSERT INTO rating_reviews (service_id, create_user, author_name, rating, review_text)
SELECT s.id, v.uid, v.author, v.rating, v.body
FROM (VALUES
    ('Маникюр у дома', 3, 'Катя', 5, 'Держится три недели, очень аккуратно.'),
    ('Маникюр у дома', 4, 'Юля', 4, 'Хорошо, чуть задержалась к записи.'),
    ('Маникюр у дома', 5, 'Ирина', 5, 'Буду записываться ещё.'),
    ('Брови и ресницы', 2, 'Лена', 5, 'Форма идеальная, не пережгла.'),
    ('Брови и ресницы', 5, 'Даша', 4, 'Чуть ярче, чем хотела, но красиво.'),
    ('Стрижка женская', 2, 'Наташа', 4, 'Стрижёт уверенно, дома чисто.'),
    ('Домашние пельмени', 2, 'Сергей', 5, 'Как у бабушки. Беру на неделю.'),
    ('Домашние пельмени', 5, 'Олег', 5, 'Борщ густой, пельмени не разварились.'),
    ('Мелкий бытовой ремонт', 2, 'Павел', 5, 'Повесил полку и починил смеситель за вечер.'),
    ('Мелкий бытовой ремонт', 3, 'Алина', 4, 'Приехал позже, но сделал на совесть.'),
    ('Уборка квартиры', 5, 'Кирилл', 5, 'После генеральной блестит плитка.'),
    ('Няня на вечер', 5, 'Мария', 5, 'Ребёнок сам просил ещё.')
) AS v(name, uid, author, rating, body)
JOIN services s ON s.name = v.name
WHERE NOT EXISTS (
    SELECT 1 FROM rating_reviews r WHERE r.service_id = s.id AND r.author_name = v.author
);

INSERT INTO rating_reviews (company_id, create_user, author_name, rating, review_text)
SELECT c.id, v.uid, v.author, v.rating, v.body
FROM (VALUES
    ('Пятёрочка на Полянах', 2, 'Анна', 4, 'Хлеб свежий, вечером очереди.'),
    ('Пятёрочка на Полянах', 5, 'Иван', 4, 'Нормальный магазин у дома.'),
    ('Аптека у дома', 3, 'Марина', 5, 'Нужное всегда есть, кассир вежливый.'),
    ('Аптека у дома', 4, 'Ольга', 4, 'Цены чуть выше сети, но близко.'),
    ('Детский клуб «Светлячок»', 2, 'Анна', 5, 'Дочка бежит на занятия сама.')
) AS v(name, uid, author, rating, body)
JOIN companies c ON c.name = v.name
WHERE NOT EXISTS (
    SELECT 1 FROM rating_reviews r WHERE r.company_id = c.id AND r.author_name = v.author
);

INSERT INTO photos (review_id, image_url, sort_order)
SELECT r.id, '/photos/nails.jpg', 0
FROM rating_reviews r
JOIN services s ON s.id = r.service_id
WHERE s.name = 'Маникюр у дома' AND r.author_name = 'Катя'
  AND NOT EXISTS (SELECT 1 FROM photos p WHERE p.review_id = r.id);
